name: Set git tag

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      pushDateTag:
        description: "Push datestamp (production) tag"
        type: boolean
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  set_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Set git tag
        run: |
          tag=$(date +'%Y%m%d')
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git tag $tag
          git push origin $tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
